### ISSUE TITLE
Waveform can have multiple WFC_LIST groups

### ISSUE THREAD

**Issue by danbodoh** [Semi-ATE/STIL#50]
This is legal STIL in the Timing block:
   bidi_time_gen_0 { 
         LHXT { 'force_pi_td_shift' Z; 'measure_po_td_shift' L/H/X/T;}
          01Z { 'force_pi_td_shift' D/U/Z;} 
}
But I get a syntax error at the '01Z'.  It appears in b_timing.lark that the grammar only allows for one set of WFC_LIST and time_offsets

**Comment by seimit** [comment]
Dear Mr. Bodoh,
Thanks for reporting this issue!
Yes, the b_timing.lark allows only one set of WFC_LIST/TimeOffset/WFE_LIST inside signal reference block. 
No problem to implement this feature.
Note that this STIL parser does not implement 100% from IEEE 1450.0. In the root folder of the project, you can see a document named "Semi-ATE_STIL_parser_coverage.ods" in which I tried to summarize what the library supports.
Kind Regards,
Seimit
