### ISSUE TITLE
Spec block name should be optional

### ISSUE THREAD

**Issue by danbodoh** [Semi-ATE/STIL#59]
lark.exceptions.UnexpectedCharacters: No terminal matches '{' in the current parser context, at line 86 col 6

Spec {
     ^
Expected one of: 
        * b_spec__SPEC_DOMAIN_NAME

Previous tokens: Token('b_spec__KEYWORD_SPEC', 'Spec')

--------

From 1450-1999 - SPEC_NAME in parens implies that it is optional

19.1 Spec and Selector block syntax
Spec (SPEC_NAME) { // this block statement defines variable values for a given category
( Category CAT_NAME {
( VAR_NAME = time_expr; )* // define only the Typ value
( VAR_NAME { (Min time_expr;) (Typ time_expr;) (Max time_expr;) } )*
} )+
}

Although a paragraph earlier implies otherwise, but I think probably a name is required only if there are multiple Spec blocks:

There may be multiple Spec blocks present. **Each Spec block shall have a domain name,** and each Spec
block name shall be unique across all Spec blocks. Spec blocks are never referenced directly; the information contained in Spec blocks is globally accessible. The defined spec variables are resolved through Category and Selector references

**Comment by seimit** [comment]
Hi Dan,
I agree with you. I made this change only because the word "shall" ignoring the spec block name in the parens.
I will revert back the code.
Regards,
Seimit
