### ISSUE TITLE
Issue 55 follow up: Selector block

### ISSUE THREAD

**Issue by danbodoh** [Semi-ATE/STIL#60]
Error:
Exception: ERROR: Trying to find value for time expression 'clock_period_td_shift', but Selector is missing in the unnamed PatternExec block
--------------

According to the specification, the Selector block name in PatternExec is optional

(page 95 definition of PatternExec)
Selector SELECTOR_NAME: An optional block to allow selection of Min, Typ, Max, and Meas values to be
used in conjunction with a PatternExec block
-----
So I assume Typ should be chosen.   In your comment on Issue 55 I don't understand what will break the rule define before use.  In my STIL file, there is neither a Selector block, nor a Selector statement in PatternExec.  And there is no Min/Typ/Max in the Category, only one equation.   So I think it is clear that missing Selector in PatternExec implies a selection of Typ; and an equation without a Min/Typ/Max label is a Typ.

**Comment by seimit** [comment]
Dear Dan,
Thank you for your time spent to ask improvements of Semi-ATE STIL library!
I already commit the changes. Let me know if all issues (except #52, I reopen it for later implementation) are fixed now.
I would like to create a new release after your confirmation.
If you find some other STIL features used by Tessent ATPG, let me know. If it is only Lark parser, I can fix is quick. If it is semantic analyzer/DumpCompiler, probably will take more time. 
Again, thank you very much for your contribution!
Kind Regards,
Seimit
